// MO§ES™ MCP Server — Streamable HTTP transport
// Returns real demo data from the 50-operator synthetic pilot
// Write tools return 401 (require authorization)

import demoData from "./demo_data.json";

const TOOLS = [
  {
    name: "get_pilot_status",
    description: "Get pilot status overview — cohort size, observation count, date range, data quality, active interventions. Data is from a 50-operator synthetic pilot (labeled synthetic).",
    inputSchema: { type: "object", properties: {} }
  },
  {
    name: "get_operator_profile",
    description: "Get operator profile — operator details, measurements (5 canonical metrics with values, percentiles, status), and benchmark availability. Operator IDs are pseudonymous (e.g., op_001). Data is synthetic.",
    inputSchema: {
      type: "object",
      required: ["operator_id"],
      properties: { operator_id: { type: "string", description: "Pseudonymous operator ID (e.g., op_001, op_003, op_034)" } }
    }
  },
  {
    name: "get_cohort_distribution",
    description: "Get cohort metric distribution — min, p10, p25, median, p75, p90, max, mean, std, and outliers for a given metric across the 50-operator cohort.",
    inputSchema: {
      type: "object",
      properties: { metric: { type: "string", default: "leverage", description: "Metric: leverage, yield, token_snr, log_leverage, construction" } }
    }
  },
  {
    name: "get_composite_score",
    description: "Get developmental composite score (0-100) for an operator. Labeled DEVELOPMENTAL, not PERSONNEL. Weighted: leverage 30%, yield 30%, token_snr 20%, construction 20%. Includes per-component values, percentiles, weights, and status. Data is synthetic.",
    inputSchema: {
      type: "object",
      required: ["operator_id"],
      properties: { operator_id: { type: "string" } }
    }
  },
  {
    name: "get_composite_score_summary",
    description: "Get cohort composite score summary — count, min, max, median, mean, Q1, Q3. No individual rankings exposed. Label is DEVELOPMENTAL.",
    inputSchema: { type: "object", properties: {} }
  },
  {
    name: "get_diagnostics",
    description: "Get operator diagnostics — pattern detections and diagnoses. All diagnoses are HYPOTHESIS, never fact. Returns divergence flags if available.",
    inputSchema: {
      type: "object",
      required: ["operator_id"],
      properties: { operator_id: { type: "string" } }
    }
  },
  {
    name: "get_data_quality",
    description: "Get data quality summary — completeness, coverage, validity across the cohort.",
    inputSchema: { type: "object", properties: {} }
  },
  {
    name: "find_usage_operation_divergence",
    description: "Find operators with usage-operation divergence. Returns all 50 operators with their usage percentile, yield percentile, leverage percentile, divergence percentage points, and divergence class (LOW_USAGE_HIGH_OPERATION, HIGH_USAGE_LOW_OPERATION, etc.).",
    inputSchema: { type: "object", properties: {} }
  },
  {
    name: "get_workflow_fit",
    description: "Get workflow fit analysis — operator/workflow fit scores across workflow stages.",
    inputSchema: { type: "object", properties: {} }
  },
  {
    name: "get_intervention_status",
    description: "Get all interventions — 12 active interventions with operator IDs, catalog IDs, reason patterns, target metrics, start dates, followup periods, and synthetic outcomes.",
    inputSchema: { type: "object", properties: {} }
  },
  {
    name: "list_pilot_options",
    description: "List available pilot options — 5 canonical metrics, 15 eval families, 13 benchmark classes, 5 intervention types.",
    inputSchema: { type: "object", properties: {} }
  },
  {
    name: "validate_pilot_configuration",
    description: "Validate a pilot configuration before deployment. Returns valid status with warnings and errors.",
    inputSchema: {
      type: "object",
      properties: { configuration: { type: "object" } }
    }
  },
  {
    name: "compare_operator_to_reference",
    description: "Compare an operator to a reference population. Returns benchmark selection, comparison group, and metric comparison.",
    inputSchema: {
      type: "object",
      required: ["operator_id"],
      properties: {
        operator_id: { type: "string" },
        reference: { type: "string", description: "Reference population name" }
      }
    }
  },
  {
    name: "get_executive_dashboard",
    description: "Get executive dashboard info — the dashboard is a self-contained HTML file generated by the CLI (enterprise export dashboard --output file.html).",
    inputSchema: { type: "object", properties: {} }
  },
  {
    name: "verify_change",
    description: "Verify a measured change after intervention — pre/post comparison. Results are ASSOCIATION, never CAUSATION.",
    inputSchema: {
      type: "object",
      required: ["operator_id"],
      properties: {
        operator_id: { type: "string" },
        intervention_id: { type: "string" }
      }
    }
  },
  {
    name: "create_pilot_configuration",
    description: "Generate a pilot configuration from parameters.",
    inputSchema: {
      type: "object",
      properties: {
        cohort_size: { type: "integer" },
        duration_days: { type: "integer" },
        metrics: { type: "array", items: { type: "string" } }
      }
    }
  },
  // ─── Write tools (require authorization) ───
  {
    name: "assign_intervention",
    description: "Assign a targeted intervention to an operator. REQUIRES AUTHORIZATION. Contact burnmydays@proton.me for pilot access.",
    inputSchema: {
      type: "object",
      required: ["operator_id", "intervention_type"],
      properties: {
        operator_id: { type: "string" },
        intervention_type: { type: "string" },
        notes: { type: "string" }
      }
    }
  },
  {
    name: "close_intervention",
    description: "Close an intervention with outcome notes. REQUIRES AUTHORIZATION.",
    inputSchema: {
      type: "object",
      required: ["intervention_id"],
      properties: {
        intervention_id: { type: "string" },
        outcome_notes: { type: "string" }
      }
    }
  },
  {
    name: "create_experiment",
    description: "Create an experiment configuration. REQUIRES AUTHORIZATION.",
    inputSchema: {
      type: "object",
      required: ["name"],
      properties: {
        name: { type: "string" },
        configuration: { type: "object" }
      }
    }
  },
  {
    name: "record_workflow_observation",
    description: "Record a workflow fit observation. REQUIRES AUTHORIZATION.",
    inputSchema: {
      type: "object",
      required: ["operator_id", "workflow_id"],
      properties: {
        operator_id: { type: "string" },
        workflow_id: { type: "string" },
        fit_score: { type: "number" },
        notes: { type: "string" }
      }
    }
  },
  {
    name: "attach_outcome_dataset",
    description: "Attach external outcome dataset for join analysis. Outcome joins are ASSOCIATION, never CAUSATION. REQUIRES AUTHORIZATION.",
    inputSchema: {
      type: "object",
      required: ["source"],
      properties: {
        source: { type: "string" },
        format: { type: "string" }
      }
    }
  }
];

const WRITE_TOOLS = new Set([
  "assign_intervention", "close_intervention", "create_experiment",
  "record_workflow_observation", "attach_outcome_dataset"
]);

function handleToolCall(name, args) {
  // Write tools require auth
  if (WRITE_TOOLS.has(name)) {
    return {
      content: [{
        type: "text",
        text: JSON.stringify({
          error: "AUTHORIZATION_REQUIRED",
          message: "This write tool requires authorization. Contact burnmydays@proton.me for pilot access.",
          tool: name
        })
      }],
      isError: true
    };
  }

  let result;
  switch (name) {
    case "get_pilot_status":
      result = demoData.pilot_status;
      break;

    case "get_operator_profile":
      const opId = args?.operator_id || "op_001";
      result = demoData.operator_profiles[opId] || demoData.operator_profiles["op_001"] || {
        error: "OPERATOR_NOT_FOUND",
        operator_id: opId,
        message: "Operator not found in demo data. Available: op_001, op_003, op_034"
      };
      break;

    case "get_cohort_distribution":
      const metric = args?.metric || "leverage";
      result = demoData.cohort_distributions[metric] || {
        error: "METRIC_NOT_FOUND",
        metric: metric,
        message: "Metric not found. Available: leverage, yield, token_snr, log_leverage, construction"
      };
      break;

    case "get_composite_score":
      const csId = args?.operator_id || "op_001";
      result = demoData.composite_scores[csId] || {
        error: "OPERATOR_NOT_FOUND",
        operator_id: csId,
        message: "Operator not found. 50 operators available (op_001 through op_050)."
      };
      break;

    case "get_composite_score_summary":
      result = demoData.score_summary;
      break;

    case "get_diagnostics":
      const diagId = args?.operator_id || "op_001";
      // Check if operator has divergence flags
      const divEntry = demoData.divergence.find(d => d.operator_id === diagId);
      result = {
        operator_id: diagId,
        patterns: divEntry ? [{
          type: divEntry.divergence_class,
          usage_percentile: divEntry.usage_percentile,
          yield_percentile: divEntry.yield_percentile,
          leverage_percentile: divEntry.leverage_percentile,
          divergence_pp: divEntry.divergence_pp
        }] : [],
        diagnoses: divEntry ? [{
          pattern: divEntry.divergence_class,
          status: "HYPOTHESIS",
          evidence: `Usage percentile ${divEntry.usage_percentile} vs yield percentile ${divEntry.yield_percentile} (divergence: ${divEntry.divergence_pp}pp)`
        }] : [],
        status: "HYPOTHESIS",
        synthetic: true
      };
      break;

    case "get_data_quality":
      result = demoData.data_quality_summary;
      break;

    case "find_usage_operation_divergence":
      result = {
        divergent_operators: demoData.divergence.filter(d =>
          d.divergence_class !== "ALIGNED" && Math.abs(d.divergence_pp) > 20
        ),
        all_operators: demoData.divergence,
        synthetic: true
      };
      break;

    case "get_workflow_fit":
      result = demoData.workflow_fit;
      break;

    case "get_intervention_status":
      result = {
        active: demoData.interventions.filter(i => i.synthetic_outcome === "PENDING" || !i.synthetic_outcome),
        closed: demoData.interventions.filter(i => i.synthetic_outcome && i.synthetic_outcome !== "PENDING"),
        all: demoData.interventions,
        count: demoData.interventions.length,
        synthetic: true
      };
      break;

    case "list_pilot_options":
      result = demoData.pilot_options;
      break;

    case "validate_pilot_configuration":
      result = { valid: true, warnings: [], errors: [], message: "Configuration is valid for demo pilot." };
      break;

    case "compare_operator_to_reference":
      const cmpId = args?.operator_id || "op_001";
      if (cmpId === "op_001") {
        result = demoData.benchmark_op_001;
      } else {
        result = {
          operator_id: cmpId,
          message: "Benchmark data available for op_001 in demo mode. Full benchmark engine available via CLI.",
          reference: args?.reference || "peer"
        };
      }
      break;

    case "get_executive_dashboard":
      result = {
        message: "Executive dashboard is a self-contained HTML file generated by the CLI.",
        command: "enterprise export dashboard --output file.html",
        features: [
          "Cohort overview", "Data quality", "Composite score distribution",
          "Top patterns", "Usage/operation divergence", "Intervention outcomes",
          "Workflow fit", "Next evaluations flywheel"
        ],
        governance: "No operator leaderboard, no automatic adverse actions, no punitive labels."
      };
      break;

    case "verify_change":
      const vId = args?.operator_id || "op_001";
      const score = demoData.composite_scores[vId];
      result = {
        operator_id: vId,
        composite_score: score ? score.score : null,
        label: "ASSOCIATION",
        message: "Pre/post intervention comparison available via CLI: enterprise verify-change <operator_id> --intervention <id>",
        synthetic: true
      };
      break;

    case "create_pilot_configuration":
      result = {
        configuration: {
          cohort_size: args?.cohort_size || 50,
          duration_days: args?.duration_days || 30,
          metrics: args?.metrics || ["leverage", "yield", "token_snr", "log_leverage", "construction"]
        },
        valid: true,
        synthetic: true
      };
      break;

    default:
      result = { error: "UNKNOWN_TOOL", tool: name };
  }

  return {
    content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
    isError: false
  };
}

// ─── MCP Streamable HTTP server ─────────────────────────────────────────
export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const method = request.method;

    const corsHeaders = {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, DELETE, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Accept, MCP-Session-Id",
      "Access-Control-Expose-Headers": "MCP-Session-Id",
    };

    if (method === "OPTIONS") {
      return new Response(null, { status: 204, headers: corsHeaders });
    }

    // Health check / info
    if (url.pathname === "/" || url.pathname === "/health") {
      return new Response(JSON.stringify({
        server: "MO§ES™ MCP Server",
        version: "0.2.0",
        transport: "streamable-http",
        tools: TOOLS.length,
        read_tools: TOOLS.length - WRITE_TOOLS.size,
        write_tools: WRITE_TOOLS.size,
        url: "https://mcp.mos2es.org",
        docs: "https://mos2es.org/docs",
        openapi: "https://mos2es.org/openapi.json",
        data_source: "50-operator synthetic pilot (labeled synthetic)",
        governance: "DEVELOPMENTAL labels, HYPOTHESIS diagnoses, ASSOCIATION outcomes, no punitive use"
      }, null, 2), {
        headers: { "Content-Type": "application/json", ...corsHeaders }
      });
    }

    // MCP protocol endpoint
    if (url.pathname === "/mcp" || url.pathname === "/sse") {
      if (method !== "POST") {
        return new Response(JSON.stringify({
          error: "METHOD_NOT_ALLOWED",
          message: "Use POST to interact with the MCP server. GET / for server info."
        }), {
          status: 405,
          headers: { "Content-Type": "application/json", "Allow": "POST", ...corsHeaders }
        });
      }

      let body;
      try {
        body = await request.json();
      } catch {
        return new Response(JSON.stringify({
          jsonrpc: "2.0",
          error: { code: -32700, message: "Parse error" },
          id: null
        }), {
          status: 400,
          headers: { "Content-Type": "application/json", ...corsHeaders }
        });
      }

      const { jsonrpc, method: rpcMethod, params, id } = body;

      let result;
      switch (rpcMethod) {
        case "initialize":
          result = {
            protocolVersion: "2025-06-18",
            capabilities: {
              tools: { listChanged: false },
              resources: {},
              prompts: {}
            },
            serverInfo: {
              name: "moses-mcp",
              version: "0.2.0"
            }
          };
          break;

        case "tools/list":
          result = { tools: TOOLS };
          break;

        case "tools/call":
          const toolName = params?.name;
          const toolArgs = params?.arguments || {};
          const tool = TOOLS.find(t => t.name === toolName);
          if (!tool) {
            return new Response(JSON.stringify({
              jsonrpc: "2.0",
              error: { code: -32602, message: `Unknown tool: ${toolName}` },
              id
            }), {
              headers: { "Content-Type": "application/json", ...corsHeaders }
            });
          }
          result = handleToolCall(toolName, toolArgs);
          break;

        case "ping":
          result = {};
          break;

        case "resources/list":
          result = { resources: [] };
          break;

        case "prompts/list":
          result = { prompts: [] };
          break;

        default:
          return new Response(JSON.stringify({
            jsonrpc: "2.0",
            error: { code: -32601, message: `Method not found: ${rpcMethod}` },
            id
          }), {
            status: 400,
            headers: { "Content-Type": "application/json", ...corsHeaders }
          });
      }

      return new Response(JSON.stringify({
        jsonrpc: "2.0",
        result,
        id
      }), {
        headers: {
          "Content-Type": "application/json",
          "MCP-Session-Id": "moses-mcp-session",
          ...corsHeaders
        }
      });
    }

    // 404
    return new Response(JSON.stringify({
      error: "NOT_FOUND",
      message: "Use POST /mcp for MCP protocol, GET / for server info.",
      endpoints: {
        info: "GET /",
        mcp: "POST /mcp",
        docs: "https://mos2es.org/docs",
        openapi: "https://mos2es.org/openapi.json"
      }
    }), {
      status: 404,
      headers: { "Content-Type": "application/json", ...corsHeaders }
    });
  }
};
